# conf/base/parameters.yml

# Initial start date for the first run if no last_update_date is found
# This must be in YYYY-MM-DD format
#The Citywide traffic safety initiative, Vision Zero started in the year 2014, hower, the crash data is available from 2012,
# so we can set the initial date to 2012-07-01 to capture the data from the start of the Vision Zero initiative.
# Adjust as needed for your first fetch

nyc_crashes:
  initial_date: "2012-07-01"
  socrata:  
    dataset_id: "h9gi-nx95"
    domain: "data.cityofnewyork.us"
    app_token: "${globals:socrata_app_token}"
  incremental:
    date_column: "crash_date"
      # Or your preferred start date

nyc_census_tracts:
  api_key: "${globals:nyc_census_api_key}"
  request_params:
    base_url: "https://api.census.gov/data/2023/acs/acs5"
    geography: "tract"
    get: "NAME,GEO_ID,B01003_001E,B17001_001E,B17001_002E"
    state_fips: "36"
    county_fips: "005,047,061,081,085"  # Bronx, Kings, New York, Queens, Richmond

census_geometry:
  census_geometry_url: "https://www2.census.gov/geo/tiger/TIGER2023/TRACT/tl_2023_36_tract.zip" # Bronx, Kings, New York, Queens, Richmond    


  